> https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html


- using SVD method. (Not eigenvalues & eigenvectors)
- input data is centered, but not scaled beforing applying SVD

In [41]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [207]:
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt

from sklearn.decomposition import PCA, TruncatedSVD
from sklearn.datasets import load_iris

In [208]:
iris_dataset = load_iris()

In [209]:
X = iris_dataset.data
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

## PCA()

In [250]:
m0 = PCA(n_components=None)
m0.fit(X)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [253]:
m0.components_   # Vt

array([[ 0.36138659, -0.08452251,  0.85667061,  0.3582892 ],
       [ 0.65658877,  0.73016143, -0.17337266, -0.07548102],
       [-0.58202985,  0.59791083,  0.07623608,  0.54583143],
       [-0.31548719,  0.3197231 ,  0.47983899, -0.75365743]])

In [255]:
Z0 = m.transform(X)

In [256]:
m0.explained_variance_
m0.explained_variance_ratio_

array([4.22824171, 0.24267075, 0.0782095 , 0.02383509])

array([0.92461872, 0.05306648, 0.01710261, 0.00521218])

In [257]:
m0.singular_values_

array([25.09996044,  6.01314738,  3.41368064,  1.88452351])

Definition of Frobenius Norm:

$$ \|A\|_F = \Big(\sum_i \sum_j (a_{ij})^2 \Big)^{\frac{1}{2}} $$


Lemma 15.1:  if svd of $A$ is $(U, \Sigma, V^T)$, then
$$ \|A\|_F = \sqrt{\sigma_1^2 + \sigma_2^2 + \cdots + \sigma_n^2} $$


Theorem 15.2: （原书中的定理表述比较绕，以下是我的理解）

考虑最小化问题， 找矩阵A在 rank=k 矩阵空间中的、F范数意义下的最优近似：

$$ \min_{S \in \mathcal{M}} \| A - S \|_F $$

上述最小化问题的解存在

$$\exists S^* = \arg \min_{S \in \mathcal{M}} \| A - S \|_F $$

且可以通过截断奇异值分解的方式得到


$$ S^* = U \Sigma^\prime V^T $$

where
$$ \Sigma^\prime = diag(\sigma_1, \cdots, \sigma_k) $$
$$ A = U \Sigma V^T $$

In PCA ---------------------------------------------------------------

Objective: minimize Projection Error

//TODO: how do "min ProjectionError" and "max Var" related ?
总体、样本 主成分定义

In PCA ---------------------------------------------------------------

$$ ExplainedVarianceRatio = \frac{\| X_{approx, k} \|_F}{\| X \|_F} = \frac{\lambda_1 + \cdots + \lambda_k}{\sum_{i=1}^n \lambda_i}$$ 

or

$$ 1- ExplainedVarianceRatio = \frac{\| X - X_{approx, k} \|_F}{\| X \|_F} = 1 - \frac{\lambda_1 + \cdots + \lambda_k}{\sum_{i=1}^n \lambda_i} $$

In [287]:
k = 2

# centeralized, MUST
iris_dataset = load_iris()
X = iris_dataset.data
X = X - X.mean(axis=0)


m = PCA(n_components=k)
m.fit(X)
Z = m.transform(X)
X_approx = m.inverse_transform(Z)

def FrobeniusNorm(A):
    return np.sqrt(np.sum(A**2))

(FrobeniusNorm(X_approx) / FrobeniusNorm(X))**2
sum(m.explained_variance_ratio_)                   # equal  (X need to be centralized)

(FrobeniusNorm(X - X_approx) / FrobeniusNorm(X))**2
1 - sum(m.explained_variance_ratio_)                   # equal  (X need to be centralized)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

0.9776852063187959

0.977685206318795

0.02231479368120514

0.022314793681205036

In [289]:
# |X|_F = sqrt(sum sigular_values^2)

FrobeniusNorm(X)
np.sqrt(np.sum(m0.singular_values_ ** 2))  # equal

FrobeniusNorm(X_approx)
np.sqrt(np.sum(m.singular_values_ ** 2))   # equal

26.103076447039722

26.103076447039726

25.810190926077272

25.810190926077265

In [247]:
# m.components_  is the Vt of 
#      U,S,Vt = svd(1/sqrt(m-1) X)
# transform X to Z:   Z = Vt dot X
# X_approx = V dot Z

Vt = m.components_
_Z = np.dot(Vt, X.T).T
_X_approx = np.dot(Vt.T, Z.T).T

abs(Z).mean()
abs(X_approx).mean()

(_Z - Z < 1e-8).all()                 # True
(_X_approx - X_approx < 1e-8).all()   # True

1.1027699505691948

0.8010042015296953

True

True