TODO: why sum to 1 ? 

In [124]:
import numpy as np

In [125]:
def generate_M(dim=3):
    """generate matrix that columns sum to 1
    """
    return np.array([np.random.choice([1/n] * n + [0] * (dim-n), replace=False, size=dim) for n in np.random.choice(np.arange(1, dim+1), dim)]).T

def generate_R_smoother(dim=3):
    return np.repeat(1/dim, dim)[None].T

In [141]:
M = generate_M(dim=5)
M

array([[0.  , 0.  , 0.2 , 0.2 , 0.25],
       [1.  , 1.  , 0.2 , 0.2 , 0.  ],
       [0.  , 0.  , 0.2 , 0.2 , 0.25],
       [0.  , 0.  , 0.2 , 0.2 , 0.25],
       [0.  , 0.  , 0.2 , 0.2 , 0.25]])

In [142]:
R0 = R_smoother = generate_R0(dim=5)
R0

array([[0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2]])

In [157]:
def PageRank(M, d=0.85, R0=None, torlerance=None):
    
    #assert 0 <= d <= 1
    
    assert len(M.shape) == 2 and M.shape[0] == M.shape[1]
    dim = M.shape[0]   
    
    R_smoother = generate_R_smoother(dim)    
    
    if R0 is None:
        R0 = R_smoother
    else:
        assert R0.shape == (dim, 1)
    
    if torlerance is None:
        torlerance = 0.0001   # TODO: how to determin torlance?

    t = 0
    Rt = R0
    R_prev = None
    while True:
        R_prev = Rt
        Rt = d * M @ Rt + (1 - d) * R_smoother
        t += 1
        
        print('iteration # {}: \nRt = {}'.format(t, Rt))
        print('========> sum Rt = ', np.sum(Rt))
        
        if np.linalg.norm(Rt - R_prev, 2) < torlerance:
            print('stop')
            return Rt
        
        if t > 100:
            print('max iteration, stop')
            return

In [160]:
PageRank(M, 0.7, R0)

iteration # 1: 
Rt = [[0.151]
 [0.396]
 [0.151]
 [0.151]
 [0.151]]
========> sum Rt =  1.0
iteration # 2: 
Rt = [[0.128705]
 [0.48518 ]
 [0.128705]
 [0.128705]
 [0.128705]]
========> sum Rt =  1.0000000000000002
iteration # 3: 
Rt = [[0.11856078]
 [0.5257569 ]
 [0.11856078]
 [0.11856078]
 [0.11856078]]
========> sum Rt =  0.9999999999999998
iteration # 4: 
Rt = [[0.11394515]
 [0.54421939]
 [0.11394515]
 [0.11394515]
 [0.11394515]]
========> sum Rt =  1.0
iteration # 5: 
Rt = [[0.11184504]
 [0.55261982]
 [0.11184504]
 [0.11184504]
 [0.11184504]]
========> sum Rt =  1.0
iteration # 6: 
Rt = [[0.1108895 ]
 [0.55644202]
 [0.1108895 ]
 [0.1108895 ]
 [0.1108895 ]]
========> sum Rt =  0.9999999999999999
iteration # 7: 
Rt = [[0.11045472]
 [0.55818112]
 [0.11045472]
 [0.11045472]
 [0.11045472]]
========> sum Rt =  0.9999999999999999
iteration # 8: 
Rt = [[0.1102569 ]
 [0.55897241]
 [0.1102569 ]
 [0.1102569 ]
 [0.1102569 ]]
========> sum Rt =  0.9999999999999999
iteration # 9: 
Rt = [[0.1101668

array([[0.1101073],
       [0.5595708],
       [0.1101073],
       [0.1101073],
       [0.1101073]])