In [1]:
from sklearn.datasets import fetch_20newsgroups

In [2]:
import pandas as pd
import numpy as np

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [4]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [172]:
categories = ['alt.atheism', 'soc.religion.christian', 'comp.graphics', 'sci.med']

news = fetch_20newsgroups(subset='test', categories=categories)

In [173]:
len(news.data)

1502

In [174]:
D = 10     # num of documents
T = 3      # num of topics

corpus = news.data[:D]

In [175]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [176]:
tfidf_vectorier = TfidfVectorizer()
X = tfidf_vectorier.fit_transform(corpus)
X

<10x1105 sparse matrix of type '<class 'numpy.float64'>'
	with 1502 stored elements in Compressed Sparse Row format>

In [177]:
from sklearn.decomposition import TruncatedSVD

In [178]:
svd = TruncatedSVD(n_components=T)
svd.fit(X)

TruncatedSVD(algorithm='randomized', n_components=3, n_iter=5,
       random_state=None, tol=0.0)

In [179]:
# svd(X) = U, Sigma, Vt

svd.components_.shape    # (3, 1105)  Vt
svd.singular_values_     # \Sigma
Y = svd.transform(X)
Y.shape                  # (10, 3)

(3, 1105)

array([1.49063492, 1.06360748, 0.99314744])

(10, 3)

In [180]:
svd.components_

array([[ 0.01190506,  0.01529435,  0.01097223, ...,  0.08269563,
         0.01834225,  0.01365755],
       [ 0.04660161, -0.00941185, -0.00516993, ...,  0.03019482,
         0.07379828, -0.00557166],
       [ 0.00990495, -0.00998782, -0.00890718, ...,  0.12868841,
        -0.00178212, -0.04542182]])

In [185]:
words = tfidf_vectorier.get_feature_names()

In [196]:
# X

doc_word_df = pd.DataFrame(X.toarray(), columns=words)
doc_word_df.iloc[:, -100:]

tuo    tuorum    turner     turns      tuum      tuus       two  \
0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1  0.000000  0.000000  0.000000  0.043194  0.000000  0.000000  0.000000   
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
3  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4  0.015773  0.015773  0.000000  0.000000  0.015773  0.015773  0.015773   
5  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
6  0.000000  0.000000  0.187026  0.000000  0.000000  0.000000  0.000000   
7  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
9  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

       ucsd       uga        uk    ...     writings     wrote        ye  \
0  0.196723  0.000000  0.000000    ...     0.000000  0.000000  0.000000   
1  0.000000  0.000000  0.000000    ...     0.000000  0.000000  0.000000   
2  0.000000  0.000000  0.102192    ...     0.000000  0.000000  0.000000   
3  0.000000  0.000000  0.000000    ...     0.000000  0.000000  0.000000   
4  0.000000  0.000000  0.000000    ...     0.000000  0.000000  0.031546   
5  0.000000  0.000000  0.000000    ...     0.000000  0.107983  0.000000   
6  0.000000  0.000000  0.000000    ...     0.000000  0.000000  0.000000   
7  0.000000  0.069498  0.000000    ...     0.069498  0.000000  0.000000   
8  0.000000  0.000000  0.131729    ...     0.000000  0.000000  0.000000   
9  0.000000  0.000000  0.000000    ...     0.000000  0.000000  0.000000   

       year     yeast       yet    yogurt       you  zijdenbos       zip  
0  0.000000  0.000000  0.000000  0.000000  0.000000   0.000000  0.000000  
1  0.000000  0.259164  0.000000  0.129582  0.000000   0.000000  0.000000  
2  0.000000  0.000000  0.000000  0.000000  0.032267   0.000000  0.000000  
3  0.000000  0.000000  0.000000  0.000000  0.131862   0.000000  0.000000  
4  0.015773  0.000000  0.000000  0.000000  0.025402   0.000000  0.000000  
5  0.000000  0.000000  0.000000  0.000000  0.115937   0.000000  0.000000  
6  0.000000  0.000000  0.000000  0.000000  0.000000   0.000000  0.093513  
7  0.000000  0.000000  0.069498  0.000000  0.000000   0.000000  0.000000  
8  0.000000  0.000000  0.000000  0.000000  0.041593   0.000000  0.000000  
9  0.000000  0.000000  0.000000  0.000000  0.063151   0.117638  0.000000  

[10 rows x 100 columns]

In [198]:
# Y
doc_topic_df = pd.DataFrame(Y, columns=['T_{}'.format(i) for i in range(T)])
doc_topic_df

T_0       T_1       T_2
0  0.497405 -0.117004 -0.072228
1  0.564434 -0.135401 -0.203397
2  0.567044  0.044028 -0.307057
3  0.518666 -0.171532  0.472552
4  0.568593 -0.252309  0.048959
5  0.401395 -0.097920  0.594997
6  0.324522 -0.067403 -0.479094
7  0.488991 -0.153202 -0.141751
8  0.341418  0.680419  0.126093
9  0.346456  0.709679 -0.014942

In [202]:
# T

topic_word_df = pd.DataFrame(svd.components_, index=['T_{}'.format(i) for i in range(T)], columns=words)
topic_word_df.iloc[:, -100:]

tuo    tuorum    turner     turns      tuum      tuus       two  \
T_0  0.004036  0.004036  0.027315  0.010972  0.004036  0.004036  0.004036   
T_1 -0.003518 -0.003518 -0.011143 -0.005170 -0.003518 -0.003518 -0.003518   
T_2  0.000783  0.000783 -0.090844 -0.008907  0.000783  0.000783  0.000783   

         ucsd       uga        uk    ...     writings     wrote        ye  \
T_0  0.044038  0.015294  0.046320    ...     0.015294  0.019507  0.008072   
T_1 -0.020347 -0.009412  0.083208    ...    -0.009412 -0.009347 -0.007036   
T_2 -0.014406 -0.009988 -0.014973    ...    -0.009988  0.065139  0.001566   

         year     yeast       yet    yogurt       you  zijdenbos       zip  
T_0  0.004036  0.065833  0.015294  0.032917  0.082696   0.018342  0.013658  
T_1 -0.003518 -0.031020 -0.009412 -0.015510  0.030195   0.073798 -0.005572  
T_2  0.000783 -0.053443 -0.009988 -0.026722  0.128688  -0.001782 -0.045422  

[3 rows x 100 columns]

## TruncatedSVD

truncated_svd.components_  is  Vt

In [157]:
from sklearn.decomposition import TruncatedSVD
from numpy.linalg import svd
import numpy as np


mtx = np.array([
    [1, 2, 3],
    [20, 10, 9],
])

sk_tsvd = TruncatedSVD(n_components=2)
sk_tsvd.fit(mtx)

y = sk_tsvd.transform(mtx)   # U \Sigma  (k-truncated)

TruncatedSVD(algorithm='randomized', n_components=2, n_iter=5,
       random_state=None, tol=0.0)

In [158]:
y

array([[ 2.80936317,  2.47133134],
       [24.10222027, -0.28805924]])

In [159]:
sk_tsvd.components_     # Vt (k-truncated)

array([[ 0.82344754,  0.41888066,  0.3827181 ],
       [-0.53143954,  0.33310471,  0.77885382]])

In [160]:
U, s, Vt = svd(mtx)
s
Sigma = np.zeros_like(mtx)
np.fill_diagonal(Sigma, s)

U
Sigma
Vt

array([24.26539807,  2.48806285])

array([[-0.11577651, -0.99327529],
       [-0.99327529,  0.11577651]])

array([[24,  0,  0],
       [ 0,  2,  0]])

array([[-0.82344754, -0.41888066, -0.3827181 ],
       [ 0.53143954, -0.33310471, -0.77885382],
       [ 0.1987616 , -0.84473679,  0.49690399]])

In [161]:
U @ Sigma @ Vt

array([[ 1.23232971,  1.82564636,  2.61066692],
       [19.75289861,  9.90839996,  8.94312048]])

In [163]:
mtx

array([[ 1,  2,  3],
       [20, 10,  9]])

In [164]:
y

array([[ 2.80936317,  2.47133134],
       [24.10222027, -0.28805924]])

In [166]:
U @ Sigma

array([[ -2.7786363 ,  -1.98655058,   0.        ],
       [-23.83860693,   0.23155303,   0.        ]])

In [170]:
Vt

array([[-0.82344754, -0.41888066, -0.3827181 ],
       [ 0.53143954, -0.33310471, -0.77885382],
       [ 0.1987616 , -0.84473679,  0.49690399]])

In [171]:
sk_tsvd.components_

array([[ 0.82344754,  0.41888066,  0.3827181 ],
       [-0.53143954,  0.33310471,  0.77885382]])