In [1]:
import numpy as np

In [26]:
x = np.array([
    [[1,2,3], 
     [4,5,6]],
    [[100, 200, 300],
     [400, 500, 600]]
])

In [32]:
np.max(x), np.amax(x)   # equivalent function

(600, 600)

In [34]:
np.amax(x, axis=-1)     # axis=-1, the last axis

array([[  3,   6],
       [300, 600]])

In [35]:
np.asarray([1,2,3])

array([1, 2, 3])

In [36]:
np.asarray((1,2,3))

array([1, 2, 3])